### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by soispha** [Duckonaut/hyprload#16]
I would like to package this for NixOS ([relevant issue](https://github.com/NixOS/nixpkgs/issues/247740)). Unfortunately the lack of a license means that this is to be treated as unfree code, which would make using and redistributing it very hard and cumbersome. I'd would be wonderful, if you could add a Foss license, preferably a FSF approved one like the GPL or LGPL. Of course, if you intended this to be a proprietary application, you can just close the issue.

**Comment by Duckonaut** [comment]
Oh, I'm gonna license it under BSD-3, same as Hyprland itself. Thought i did already tbh 😅. I don't have access to a PC rn, if you introduce it via PR I can approve it
